### ISSUE TITLE
[Feature request] Publish pictures

### ISSUE THREAD

**Issue by cnschu** [shapkinaa/noteson-obsidian-plugin#2]
A linked image attachment in obsidian should be uploaded/published and linked so that it is dispplayed ob the published page like in obsidian.

**Comment by shapkinaa** [comment]
Update your plugin to 1.0.1 version and test this function

**Comment by cnschu** [comment]
it links the picture, but is seems it doesn't upload it.
example page:
https://notes.noteson.ru/8103f5d0adfd14fdeb283e6a35db142a/default/LordAndreaBelisariusNavigator.html

**Comment by shapkinaa** [comment]
> it links the picture, but is seems it doesn't upload it. example page: https://notes.noteson.ru/8103f5d0adfd14fdeb283e6a35db142a/default/LordAndreaBelisariusNavigator.html

could you send md file of this note?

**Comment by cnschu** [comment]
[Lord Andrea Belisarius (Navigator).md](https://github.com/shapkinaa/noteson-obsidian-plugin/files/15259537/Lord.Andrea.Belisarius.Navigator.md)

**Comment by cnschu** [comment]
Also it seems that the title of the page is missing, and instead the first line of text is formatted as the title.

**Comment by shapkinaa** [comment]
> [Lord Andrea Belisarius (Navigator).md](https://github.com/shapkinaa/noteson-obsidian-plugin/files/15259537/Lord.Andrea.Belisarius.Navigator.md)

Thanks for file.
I tried to repeat your scenario.
I created a note with your text and next to it I put a picture in PNG format.
Content of my vault directory
![изображение](https://github.com/shapkinaa/noteson-obsidian-plugin/assets/9691222/5810c3f8-a0af-4d6f-95bd-585f6e4e8f40)

Content of my vault, from Obsidian. With Test note
![изображение](https://github.com/shapkinaa/noteson-obsidian-plugin/assets/9691222/d3c6d940-2be1-43df-ba9d-9a9d7e55f3dd)

And I published this note on noteson.ru server
the result is below
![изображение](https://github.com/shapkinaa/noteson-obsidian-plugin/assets/9691222/b0d88db3-a423-4800-a66b-b33c1626168b)

There is a picture on the page
I don't know how to reproduce your case yet
Dead links really look terrible, there is already a task for them.
The behavior of headings now is as follows: The title of the note goes into the title of the page, and the body of the note is placed in the body of the page.

**Comment by cnschu** [comment]
to further test this, i should remove the page from notenon.ru, but it is not possible.
if i try to use "Remove from NotesOn", i only get a short failure notification, and nothing else happens.

**Comment by cnschu** [comment]
1. reinstalled the plugin, 
2. set up my credentials anew.
3. removed the file from noteeson 
4. published another note with another picture

same error persists (no picture in the published note).
example note:
https://notes.noteson.ru/8103f5d0adfd14fdeb283e6a35db142a/default/AgentFrankHorrigan.html

i would be willing to send you any information you need to diagnose this error.

**Comment by shapkinaa** [comment]
> to further test this, i should remove the page from notenon.ru, but it is not possible. if i try to use "Remove from NotesOn", i only get a short failure notification, and nothing else happens.


please, update plugin to 1.0.2 version

**Comment by shapkinaa** [comment]
> 1. reinstalled the plugin,
> 
>     2. set up my credentials anew.
> 
>     3. removed the file from noteeson
> 
>     4. published another note with another picture
> 
> 
> same error persists (no picture in the published note). example note: https://notes.noteson.ru/8103f5d0adfd14fdeb283e6a35db142a/default/AgentFrankHorrigan.html
> 
> i would be willing to send you any information you need to diagnose this error.

In the logs on the server I don’t see a record of the image being sent.
What version of obsidian do you have?

**Comment by cnschu** [comment]
My obsidian Version is 1.5.12
i tested anew with version 1.0.2 and a new note.

Still no upload of the picture(s).

**Comment by shapkinaa** [comment]
> My obsidian Version is 1.5.12 i tested anew with version 1.0.2 and a new note.
> 
> Still no upload of the picture(s).

what operating system are you using?
could you send list of your plugins?

**Comment by cnschu** [comment]
OS: Windows 11
no other community plugins

**Comment by shapkinaa** [comment]
Could you rewrite main.js file in plugin directory?
Plugin directory placed in directory like this - ./Documents/TestPlugin/.obsidian/plugins/noteson-obsidian-plugin
Then, press Ctrl+Shift+i.
It will seem Developer Console on the right side of Obsidian window.
![изображение](https://github.com/shapkinaa/noteson-obsidian-plugin/assets/9691222/e5855c43-42d4-439c-9daa-618ffe0b3f37)

Then, publish your note (with picture) and send me screenshot of Developer Console.
![изображение](https://github.com/shapkinaa/noteson-obsidian-plugin/assets/9691222/6600dee5-e4b8-4426-bd7c-1d755b4344f9)

To hide Developer Console you could press Ctrl+Shift+i again

**Comment by shapkinaa** [comment]
[main.js.zip](https://github.com/shapkinaa/noteson-obsidian-plugin/files/15335251/main.js.zip)

**Comment by cnschu** [comment]
1) created a new vault
2) created a folder "Anlagen" to store the pictures
3) createdd a folder "test" to store the notes
4) made a small screenshot
5) pasted the screenshot into "Welcome" 
6) created a note "Unbenannt"
7) pastet some text-text and a bigger picture into it
8) published "Welcome"
9) published "Unbenannt"

it seems that the failed picture is simply too big (it is 1.54 MB).
welcome Source: [Welcome.md](https://github.com/shapkinaa/noteson-obsidian-plugin/files/15362792/Welcome.md)
published "Welcome": https://notes.noteson.ru/8103f5d0adfd14fdeb283e6a35db142a/default/Welcome.html

unbenannt source: [Unbenannt.md](https://github.com/shapkinaa/noteson-obsidian-plugin/files/15362793/Unbenannt.md)
published "Unbenannt" (faulty): https://notes.noteson.ru/8103f5d0adfd14fdeb283e6a35db142a/default/Unbenannt.html

Log:
[obsidian.md-1716028390212.log](https://github.com/shapkinaa/noteson-obsidian-plugin/files/15362797/obsidian.md-1716028390212.log)

my conclusion:
Image file size is too big.

**Comment by cnschu** [comment]
it would be nice, if ...
- the plugin accepted pictures up to 2 MB
- the plugin informed the user if the picture is too big and the upload fails.

**Comment by shapkinaa** [comment]
> it would be nice, if ...
> 
>     * the plugin accepted pictures up to 2 MB
> 
>     * the plugin informed the user if the picture is too big and the upload fails.

I fix it

**Comment by shapkinaa** [comment]
> it links the picture, but is seems it doesn't upload it. example page: https://notes.noteson.ru/8103f5d0adfd14fdeb283e6a35db142a/default/LordAndreaBelisariusNavigator.html

Please, repeat this case

**Comment by cnschu** [comment]
i no longer use noteson in the vault in question.
but i tried with the test data mentioned above :)

1) updated plugin to 1.0.3
2) "remove from NotesOn" on "Unbenannt"
3) "Publish (or Update) note to NotesOn" on "Unbenannt"
4) no picture uploaded 

Link:
https://notes.noteson.ru:443/8103f5d0adfd14fdeb283e6a35db142a/default/Unbenannt.html

Log:
[obsidian.md-1716219605165.log](https://github.com/shapkinaa/noteson-obsidian-plugin/files/15378959/obsidian.md-1716219605165.log)

**Comment by shapkinaa** [comment]
fix bug. When pictures was placed in different folders, may be pictures not showed on page
